python apex_oracle_constrained_diverse_optimization.py \
    --task_id apex \
    --divf_id edit_dist \
    --max_n_oracle_calls 1000000 \
    --bsz 50 \
    --track_with_wandb True \
    --constraint_function_ids "[similarity]" \
    --constraint_thresholds "[0.75]" \
    --constraint_types "[GHLLIHLIGKATLAL]" \
    --wandb_entity YOUR_WANDB_ENTITY \
    --num_initialization_points 10000 \
    --dim 256 \
    --max_string_length 30 \
    --M 20 \
    --tau 1 \
    --task_specific_args "[gramnegonly_mean]" \
    - run_robot - done
